services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - CodeGems-Back/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./CodeGems-Back
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - CodeGems-Back/.env

  next-app:
    container_name: next-app
    build:
      context: ./CodeGems-Front
      dockerfile: Dockerfile
      args:
        NEXTAUTH_URL: http://localhost:8080
        NEXTAUTH_SECRET: senhamuitoforte
        GOOGLE_CLIENT_SECRET: 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
        GITHUB_CLIENT_SECRET: 88d9aebc697450622c51608634f2b79c47a03b3b
    restart: always
    ports:
      - 3000:3000

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - postgres
      - node
      - next-app

volumes:
  postgres-volume:

