services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - CodeGems-Back/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./CodeGems-Back
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - CodeGems-Back/.env

  next-app:
    container_name: next-app
    build: ./CodeGems-Front
    restart: always
    ports:
      - 3000:3000
    volumes:
      - react-volume: ./
    depends_on:
      - postgres
      - node


  # nginx:
  #   container_name: nginx_app
  #   build: ./nginx
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - react-volume:/var/www/html
  #   depends_on:
  #     - postgres
  #     - node
  #     - react

volumes:
  postgres-volume:
  react-volume:

