services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - CodeGems-Back/.env.test

  node:
    container_name: node
    build: ./CodeGems-Back
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - CodeGems-Back/.env.test



